"pattern_name: pattern
collar_style.value: collar_style
cable_length.value: cable
material.value: material
item_name.value: item_name
fabric_type.value: fabric_type
care_instructions.value: care_instructions
water_resistance_level.value: water_resistance_level
operating_system.value: operating_system
connectivity_technology.value: connectivity_technology
display.size.value: display
mounting_type.value: mounting_type
minimum_weight_recommendation.value: minimum_weight_recommendation
color.value: color
brand.value: brand
size.value: size
item_weight.value: item_weight
size.value: size
included_components.value: included_components
assembly_instructions.value: assembly_instructions
battery.average_life.value: battery_average_life_recharge
compatible_phone_models.value: compatible_phone_models
compatible_devices.value: compatible_devices
compatible_mountings.value: compatible_mountings
focus_type.value: focus_type
lens.type.value: lens
min_focal_length.value: min_focal_length
flavor.value: flavor
special_feature.value: special_feature
wireless_communication_technology.value: wireless_communication_technology
item_shape.value: item_shape
maximum_weight_recommendation.value: maximum_weight_recommendation
display.resolution_maximum.value: display
image_contrast_ratio.value: image_contrast_ratio
fit_type.value: fit_type
breed_recommendation.value: breed_recommendation
ingredients.value: ingredients
finish_type.value: finish_type
style.value: style
max_aperture.value: max_aperture
max_focal_length.value: max_focal_length
maximum_aperture_range.value: maximum_aperture_range
min_aperture.value: min_aperture
model_name.value: model_name
closure.type.value: closure
item_length_description.value: item_length_description
neck.neck_style.value: neck
sleeve.type.value: sleeve
brightness.value: brightness
display.technology.value: display
bottom_style.value: bottom_style
sole_material.value: sole_material
waist.size.value: waist
form_factor.value: form_factor
manufacturer_minimum_age.value: manufacturer_minimum_age
front_style.value: front_style
inseam.length.value: inseam
leg.style.value: leg
pocket_description.value: pocket_description
Power Source: power_source_type
Hair Type: hair_type
